source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
#第三方库导入需要谨慎---防止单元测试框架编译失败---

target 'DingTalkCalendar' do

     pod 'Aspects', '~> 1.4.1'
     
     pod 'SnapKit', '~> 4.0.0'
     
     pod 'SDWebImage', '~> 4.3.2'
    
end

target 'DingTalkCalendarTests' do
    
    pod 'Aspects', '~> 1.4.1'
    
    pod 'SnapKit', '~> 4.0.0'
    
    pod 'SDWebImage', '~> 4.3.2'
    
end
